### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jonny7**
Update based on discussion with Tanner on Discord

### CODE REVIEW

**Comment by jdmcd** [comment]
A few things here:

1. This PR should move to the PR currently open on vapor/documentation 

2. I don’t think this is correct. The ‘make’ call in the controller should not be making the specific type, it should be making the generic type so that tests can sub in other implementations. Does that make sense? 

Thank you for contributing!

**Comment by jonny7** [comment]
No problem Jimmy,

Ok, I think if you try to `make` for the generic type then you'll encounter the error: `No services are available for UserRepository`.  But at the same time, you can't register the service for UserRepository as it it doesn't conform to `ServiceFactory`.  Based on what @tanner0101 said in Discord, I just conformed to `ServiceType`. So I'm fine with this, not being merged in, if there are pieces not quite right 😄

**Comment by jdmcd** [comment]
Yeah something is off, I would love to figure out the best way to do it. @tanner0101 when you get a chance can you clarify how to register the concrete implementations for the generic types?

**Comment by jdmcd** [comment]
Per the conversation in Discord, these changes have been made over at the documentation PR. See the update to support easier service registration here: https://github.com/vapor/documentation/pull/347/commits/2c6b089bd9b1ff225771a0e58f2cb4fbd3ec4edf#diff-f048bd6534d357bb38396ff54b7ab259L404

**Pull request closed without merging**
